security:
  basic:
    enabled: false

management:
  security:
    enabled: false

logging:
  level:
    com:
      example:
        testgreetingconfig: DEBUG

greeting:
  displayFortune: true

quoteServiceURL: git@github.com:abiscayart/app-config.git